server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${ORDER_DB_USER:orders}
    password: ${ORDER_DB_PASS:orders}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.tcc: DEBUG
