server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${INVENTORY_DB_USER:inventory}
    password: ${INVENTORY_DB_PASS:inventory}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.tcc: DEBUG

